repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
        args:
          - --config
          - .code_quality/pyproject_black.toml